#!/bin/bash

function pause(){
   read -p "$*"
}

echo "mcs *.cs";
mcs *.cs; 
echo "./*.exe";
echo "--------";
echo;
./*.exe;


#echo "file=$1";
#echo "dpi=$2";
#echo "$0 $1 $2";
#pdf2djvu $1 -o "$1".djvu --dpi=$2;

pause 'Press [Enter] key to continue...';



