#!/bin/bash

function pause(){
   read -p "$*"
}

sleep 1;

# удаление кавычек
# изначально $1 имеет вид '/path/1.pdf'

str=$1;
b=$((${#str}-2));
file=${str:1:$b};

echo "file=$file";
echo "dpi=$2";
echo "$0 $file $2";
pdf2djvu $file -o "$file[$2dpi]".djvu --dpi=$2 --no-page-titles;
# 
pause 'Press [Enter] key to continue...';



