#!/bin/bash
# 1111111111111111111

function pause(){
   read -p "$*"
}

echo "file=$1";
echo "dpi=$2";
echo "$0 $1 $2";
pdf2djvu $1 -o "$1".djvu --dpi=$2;
pause 'Press [Enter] key to continue...';



