#!/bin/bash

killall mplayer;

case $1 in
	
	0)
          exit 0
          ;;
          
	1)   # germany        
          mplayer http://phoenix-powerradio.com:8010/
          ;;

  	2)   # germany        
          mplayer http://188.40.107.198:21200/stream/1/
          ;;

         
	3)   # germany        
          mplayer http://mp3channels.webradio.antenne.de:80/antenne
          ;;
          
	4)   # germany - relax          
          mplayer -playlist http://stream.absolutradio.de/relax/mp3-128/listenlive.m3u
          ;;
          
	5)	 	# germany        
         mplayer http://mp3channels.webradio.antenne.de:80/antenne          
         ;;
	
	6)		# germany        
         mplayer http://ga-stream01.ga-bonn.de:80/live128      
         ;;   

	7)		# Beijing Joy FM
         mplayer http://80.237.159.25:8100/
         ;; 
          
	8)    #jap
         mplayer -playlist http://japanradio.ru/playlist.m3u
         ;; 
          
	9)		# china
         mplayer http://219.142.120.27/chn
         ;; 

         
   *)   # ПОКА ЭТО НАМ НЕ НУЖНО! но можно будет вернуть.
			# от 1 до 4
			echo "radio=$1";
         mplayer http://www.bbc.co.uk/radio/listen/live/r$1_aaclca.pls;
         ;;
esac

#if [ $1 -eq '0' ]; then
	#exit 0;
#fi	

#if [ $1 -eq '5' ]; then
#	mplayer -playlist http://japanradio.ru/playlist.m3u
#fi	

#mplayer http://www.bbc.co.uk/radio/listen/live/r$1_aaclca.pls;


