#!/bin/bash
sync;

a=`cat /sys/block/sdc/removable`
echo "res sdb = $a"

if [ $a -eq '0' ]; then
	sudo umount /dev/sdb;
	sudo hdparm -y /dev/sdb;
	sleep 1;
	sudo hdparm -Y /dev/sdb;
	exit 0
fi

a=`cat /sys/block/sdd/removable`
echo "res sdd = $a"


if [ $a -eq '0' ]; then
	sudo umount /dev/sdd;
	sudo hdparm -y /dev/sdd;
	sleep 1;
	sudo hdparm -Y /dev/sdd;
	exit 0
fi

