#!/bin/bash
# 1111111111111111111

function pause(){
   read -p "$*"
}

pause 'Press [Enter] key to begin zip directory';

curdir=$(pwd);
path=$1;
echo "curdir=$curdir";
echo "path=$path";
new="$path";
echo "new=$new";

tar zcvf $new.tar.gz $new;
echo "------------------";
echo "tar zcvf $new.tar.gz $new";
echo "ok"
#sleep 20;
pause 'Press [Enter] key to continue...';

