#!/bin/bash
# выключить винчестер hdb (standby) - нужны права ROOT
sudo mount /dev/sdb1 /mnt/usb -t vfat -o rw,umask=0,iocharset=utf8
sudo mount /dev/sdc1 /mnt/usb2 -t vfat -o rw,umask=0,iocharset=utf8
